### ISSUE TITLE
Unable to run/build in iOS when using along with `cloud_firestore`

### ISSUE THREAD

**Issue by samyakb-work** [Web3Auth/single-factor-auth-flutter#4]
Hey Devs,

I am facing an issue while using your package along with [`cloud_firestore`](https://pub.dev/packages/cloud_firestore). This is working just fine in Android, but facing the issue in iOS.

In iOS, `single_factor_auth_flutter` depends on **OpenSSL** whereas `cloud_firestore` depends on **BoringSSL** ([BoringSSL](https://firebaseopensource.com/projects/firebase/boringssl/) is a fork of OpenSSL that is designed to meet Google's needs).

When using both the packages simultaneously, BoringSSL is tampering with OpenSSL files, which is manipulating it's header files.

As a result we are getting the following error while running for iOS:

```
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'openssl_grpc/base.h' file not found
/Users/cumulations/Desktop/flutter_apps/w3a_spm_issue_demo/ios/Pods/BoringSSL-GRPC/src/include/openssl/aes.h:51:9
```

Here is a [minimal reproducible example](https://github.com/samyakb-work/w3a_spm_issue_demo). In this, I have just added `cloud_firestore` and `single_factor_auth_flutter` and trying to build for iOS.

Here are some system info:
- Flutter version:
  ```
  Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision d211f42860 (7 weeks ago) • 2023-10-25 13:42:25 -0700
  Engine • revision 0545f8705d
  Tools • Dart 3.1.5 • DevTools 2.25.0
  ```
- Xcode version:
  ```
  Xcode 14.3.1
  Build version 14E300c
  ```

**Comment by grvgoel81** [comment]
This is the issue assciated with cloud_firestore sdk in iOS. Attaching some post relates to it:

https://stackoverflow.com/questions/67822031/fatal-error-openssl-x509-h-file-not-found-in-flutter-ios-build-after-integrat
https://stackoverflow.com/questions/59128847/xcode-grpc-core-error-openssl-grpc-ssl-h-file-not-found
https://stackoverflow.com/questions/50111556/openssl-base-h-file-not-found-firestore
https://github.com/CocoaPods/CocoaPods/issues/10772
https://github.com/firebase/firebase-ios-sdk/issues/4007
